namespace BarberBoss.Exception;

/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the Visual Studio Code Extension PrateekMahendrakar.resxpress
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class ResourceErrorMessages 
{
	private static global::System.Resources.ResourceManager resourceMan;
	[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
	public ResourceErrorMessages()
	{
	}
	/// <summary>
	///   Returns the cached ResourceManager instance used by this class.
	/// </summary>
	[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
	public static global::System.Resources.ResourceManager ResourceManager
	{
		get
		{
			if (object.ReferenceEquals(resourceMan, null))
			{
				global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BarberBoss.Exception.ResourceErrorMessages", typeof(ResourceErrorMessages).Assembly);
				resourceMan = temp;
			}
			return resourceMan;
		}
	}
	/// <summary>
	///   Overrides the current thread's CurrentUICulture property for all
	///   resource lookups using this strongly typed resource class.
	/// </summary>
	[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
	public static global::System.Globalization.CultureInfo Culture { get; set; }
	
	/// <summary>
	/// Looks up a localized string similar to Unknown error..
	/// </summary>
	public static string UNKNOWN_ERROR => ResourceManager.GetString("UNKNOWN_ERROR", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Healthy..
	/// </summary>
	public static string HEALTH => ResourceManager.GetString("HEALTH", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Billing date cannot be in the future..
	/// </summary>
	public static string BILLING_DATE_CANNOT_BE_FUTURE => ResourceManager.GetString("BILLING_DATE_CANNOT_BE_FUTURE", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Barber name is required..
	/// </summary>
	public static string BARBER_NAME_REQUIRED => ResourceManager.GetString("BARBER_NAME_REQUIRED", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Client name is required..
	/// </summary>
	public static string CLIENT_NAME_REQUIRED => ResourceManager.GetString("CLIENT_NAME_REQUIRED", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Service name is required..
	/// </summary>
	public static string SERVICE_NAME_REQUIRED => ResourceManager.GetString("SERVICE_NAME_REQUIRED", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Amount must be greater than zero..
	/// </summary>
	public static string AMOUNT_MUST_BE_GREATER_THAN_ZERO => ResourceManager.GetString("AMOUNT_MUST_BE_GREATER_THAN_ZERO", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Invalid payment method..
	/// </summary>
	public static string INVALID_PAYMENT_METHOD => ResourceManager.GetString("INVALID_PAYMENT_METHOD", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Invalid status..
	/// </summary>
	public static string INVALID_STATUS => ResourceManager.GetString("INVALID_STATUS", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Billing not found..
	/// </summary>
	public static string BILLING_NOT_FOUND => ResourceManager.GetString("BILLING_NOT_FOUND", Culture);
}
