namespace BarberBoss.Domain.Reports;

/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the Visual Studio Code Extension PrateekMahendrakar.resxpress
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class ResourceReportGenerationMessages 
{
	private static global::System.Resources.ResourceManager resourceMan;
	[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
	public ResourceReportGenerationMessages()
	{
	}
	/// <summary>
	///   Returns the cached ResourceManager instance used by this class.
	/// </summary>
	[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
	public static global::System.Resources.ResourceManager ResourceManager
	{
		get
		{
			if (object.ReferenceEquals(resourceMan, null))
			{
				global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BarberBoss.Domain.Reports.ResourceReportGenerationMessages", typeof(ResourceReportGenerationMessages).Assembly);
				resourceMan = temp;
			}
			return resourceMan;
		}
	}
	/// <summary>
	///   Overrides the current thread's CurrentUICulture property for all
	///   resource lookups using this strongly typed resource class.
	/// </summary>
	[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
	public static global::System.Globalization.CultureInfo Culture { get; set; }
	
	/// <summary>
	/// Looks up a localized string similar to Title.
	/// </summary>
	public static string TITLE => ResourceManager.GetString("TITLE", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Date.
	/// </summary>
	public static string DATE => ResourceManager.GetString("DATE", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Payment type.
	/// </summary>
	public static string PAYMENT_METHOD => ResourceManager.GetString("PAYMENT_METHOD", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Amount.
	/// </summary>
	public static string AMOUNT => ResourceManager.GetString("AMOUNT", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Description.
	/// </summary>
	public static string DESCRIPTION => ResourceManager.GetString("DESCRIPTION", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Cash.
	/// </summary>
	public static string CASH => ResourceManager.GetString("CASH", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Credit card.
	/// </summary>
	public static string CREDIT_CARD => ResourceManager.GetString("CREDIT_CARD", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Debit card.
	/// </summary>
	public static string DEBIT_CARD => ResourceManager.GetString("DEBIT_CARD", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Pix.
	/// </summary>
	public static string PIX => ResourceManager.GetString("PIX", Culture);
	
	/// <summary>
	/// Looks up a localized string similar to Other.
	/// </summary>
	public static string OTHER => ResourceManager.GetString("OTHER", Culture);
}
